fixed versions for openjdk

diff --git a/install-programs b/install-programs
--- a/install-programs
+++ b/install-programs
@@ -3,11 +3,11 @@
 set -euo pipefail
 
 declare -A versions=()
-versions[oracleJdk]=1.9.0-1
-versions[openjdk]=jdk8u172-b11
 versions[apache-maven]=3.5.2
-versions[dbeaver]=5.0.5
+versions[dbeaver]=5.2.4
 versions[sts]=3.9.2
+versions[openjdk8]=8u191-b12
+versions[openjdk9]="jdk-9+181"
 baseDir=$HOME/programs
 
 #
@@ -23,7 +23,7 @@ downloadExctractLink() {
   local urlChecksum="${3:-}"
   local targetDir=$baseDir/${4:-$name}
   local stripComponents=${5:-1}
-  local extractDir=$targetDir/$name-${versions[$name]}
+  local extractDir=$targetDir/$name-${versions[$name]:-$6}
   local filename="$targetDir/${url##*/}"
   local expectedChecksum actualChecksum
 
@@ -33,8 +33,14 @@ downloadExctractLink() {
   [[ -f "$filename" ]] || curl -L --fail --progress-bar -o "$filename" "$url" || return 2
   if [[ -n "${urlChecksum}" ]] && [[ "${urlChecksum}" != "skip" ]]; then
     sumprog=${urlChecksum%%:*}
+    echo "sumprog: $sumprog"
     urlChecksum=${urlChecksum#*:}
-    expectedChecksum=$(curl -L --fail --silent "$urlChecksum" | cut -d' ' -f1) || return 3
+    echo "urlChecksum: $urlChecksum"
+    if ! expectedChecksum=$(curl -L --fail --silent "$urlChecksum" | cut -d' ' -f1); then
+      echo "Could not fetch checksum"
+      return 3
+    fi
+    echo "expected checksum: $expectedChecksum"
     actualChecksum=$($sumprog < "$filename" | sed -e 's/[ -]//g') || return 4
     if [[ "$expectedChecksum" != "$actualChecksum" ]]; then
       echo "Checksum mismatch ($sumprog)"
@@ -65,36 +71,6 @@ installMaven() {
     "https://www.apache.org/dist/maven/maven-3/${versions[$name]}/binaries/apache-maven-${versions[$name]}-bin.tar.gz.sha1"
 }
 
-installJavaOracle() {
-  local javaDir=$baseDir/java
-  local jdkJson url jdkVersion jdkDir
-
-  echo "Downloading JDK versions info"
-
-  jdkJson=$(curl -L --fail "https://raw.githubusercontent.com/shyiko/jabba/master/index.json")
-  echo "Downloadable JDK versions:"
-  jq '.linux.amd64.jdk | keys' <<< "$jdkJson"
-  url=$(jq -r ".linux.amd64.jdk.\"${versions[java-oracle]}\"" <<< "$jdkJson")
-  [[ -n $url ]] || { echo "Don't know how to download version ${versions[java-oracle]}"; return 1; }
-  url=${url//tgz\+/}
-
-  local filename="$javaDir/${url##*/}"
-
-  echo "Downloading JDK ${versions[java-oracle]}"
-  echo "  from $url"
-  [[ -d "$javaDir" ]] || mkdir -p "$javaDir"
-  [[ -f "$filename" ]] || curl -L --fail --cookie "oraclelicense=accept-securebackup-cookie" -o "$filename" "$url" || return 2
-  
-  echo "Extracting ${filename##*/}..."
-  tar xf "$filename" -C "$javaDir"
-  echo "Creating symlink..."
-  jdkVersion=$(awk -F '.' '{print $2}' <<< "${versions[java-oracle]}")
-  jdkDir=$(tar -t --exclude='*/*/*' -f "$filename" | cut -d'/' -f1 | uniq)
-  ln -sfT "$jdkDir" "$javaDir/java$jdkVersion"
-  ln -sfT "java$jdkVersion" "$javaDir/current"
-  echo "Done."
-}
-
 installDBeaver() {
   local name=dbeaver ini=$baseDir/dbeaver/current/dbeaver.ini
   downloadExctractLink \
@@ -113,12 +89,22 @@ installSTS() {
   echo -e "-vm\n$baseDir/java/current/bin\n$(cat "$ini")" > "$ini"
 }
 
-installOpenJDK() {
-  local name=openjdk
+installOpenJDK8() {
+  local name=openjdk8
   downloadExctractLink \
     "$name" \
-    "https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/${versions[$name]}/OpenJDK8_x64_Linux_${versions[$name]}.tar.gz" \
-    "sha256sum:https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/${versions[$name]}/OpenJDK8_x64_Linux_${versions[$name]}.sha256.txt" \
+    "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz" \
+    "sha256sum:https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz.sha256.txt" \
+    "java" \
+    2
+}
+
+installOpenJDK9() {
+  local name=openjdk9
+  downloadExctractLink \
+    "$name" \
+    "https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_linux_hotspot_9_181.tar.gz" \
+    "sha256sum:https://github.com/AdoptOpenJDK/openjdk9-binaries/releases/download/jdk-9%2B181/OpenJDK9U-jdk_x64_linux_hotspot_9_181.tar.gz.sha256.txt" \
     "java" \
     2
 }
@@ -131,8 +117,11 @@ while [[ -n ${1:-} ]]; do
     oracleJDK)
       installJavaOracle
       ;;
-    openjdk)
-      installOpenJDK
+    openjdk8)
+      installOpenJDK8
+      ;;
+    openjdk9)
+      installOpenJDK9
       ;;
     sts)
       installSTS;;
